'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id),W=720,H=640;canvas.height=H;
const art=new Image();art.src='assets/duck.png';
let level=0,done=false,light=true,found=0,eaten=0,stamps=0,duck={x:360,y:435},drag=null,particles=[],floaters=[],last=0,t=0,sound=false,audio=null,winTime=0,pressed=null,won=new Set();
const labels=['01 · 闭眼都会 / 入门','02 · 装进脑子 / 入门','03 · 上去写 / 入门','04 · 抓住重点 / 眼力','05 · 过耳不忘 / 记忆','06 · 别走神 / 路线','07 · 安排明白 / 排序','08 · 期末鸭轴 / 综合'];const quotes=['“这题闭着眼都会！”','“把知识装进脑子里！”','“上来，把答案写黑板上！”','“只抓重点！其他不用管！”','“我只讲一遍，记住了吗？”','“拿着重点，别走神！”','“把事情安排得明明白白！”','“学过的，要融会贯通！”'];let ex={};
let notes=[],books=[];const bookNames=['语文','数学','英语'];
function beep(freq=220,duration=.1){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sawtooth';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.58,audio.currentTime+duration);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function burst(x,y,n=22){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*480,vy:-Math.random()*440-60,life:1.3,rotation:Math.random()*6,color:['#f95a9d','#ffe04b','#51c9b1','#fff'][i%4]});}
function say(text,x=360,y=215){floaters.push({text,x,y,life:1.6});}
function reset(n=level){$('options').replaceChildren();$('action').disabled=false;level=n;done=false;light=true;found=0;eaten=0;stamps=0;drag=null;particles=[];floaters=[];duck={x:360,y:437};winTime=0;notes=[{x:140,y:200,text:'会了',hit:false},{x:568,y:250,text:'才怪',hit:false},{x:350,y:130,text:'嘎！',hit:false}];books=bookNames.map((name,i)=>({x:160+i*200,y:540,name,used:false}));$('lessonLabel').textContent=labels[n];$('quote').textContent=quotes[n];$('hint').textContent=['老师说不用看。那还开灯干什么？','把三本书拖到鸭头上。点书也能投喂。','把鸭拖到黑板上，再戳它使劲写。'][n];$('status').textContent='鸭听懂了。';$('action').textContent=['关灯，听老师的','喂一本知识','把鸭送上黑板'][n];if(n>=3)startExtra();update();}
function update(){document.querySelectorAll('nav button').forEach((b,i)=>{b.classList.toggle('active',i===level);b.classList.toggle('done',won.has(i));b.setAttribute('aria-current',i===level?'step':'false')});$('count').textContent=level>=3?extraProgress():done?'本节：超额完成':level===0?(light?'任务：先把灯关了':`找到答案 ${found} / 3`):level===1?`脑内知识 ${eaten} / 3`:`鸭式板书 ${stamps} / 6`;$('grade').textContent=`离谱学分 ${won.size} / 8`;}
function win(){if(done)return;if(level>=3){winExtra();return;}done=true;winTime=t;won.add(level);burst(360,240,70);beep(420,.3);$('status').textContent=['鸭开了远光灯。','脑子：已撑。','满黑板都是鸭的观点。'][level];$('hint').textContent=['闭眼不会。但鸭会开大灯。老师：没让你开挂。','知识进去了。鸭也站不住了。','老师：我让你写答案，没让你发表鸭见。'][level];$('action').textContent='下节课，继续听话';update();}
function feed(index){if(done||level!==1||books[index]?.used)return;books[index].used=true;eaten++;beep(190+eaten*60,.16);burst(duck.x,duck.y-110,14);say(['知识 +1','脑容量告急','知识把鸭拿捏了'][eaten-1]);$('status').textContent=['还能装。','再装就不礼貌了。','鸭：撑得很有文化。'][eaten-1];update();if(eaten===3)win();}
function stamp(){if(done||level!==2)return;duck.x=250+Math.random()*220;duck.y=245+Math.random()*65;stamps++;beep(90+Math.random()*100,.12);burst(duck.x,duck.y,12);say(stamps===6?'一鸣惊人':'嘎！',duck.x,duck.y-110);update();if(stamps===6)win();}
function action(){if(done){reset((level+1)%8);return}if(level>=3){extraAction();return}if(level===0){if(light){light=false;beep(140,.3);$('hint').textContent='鸭自带远光灯。拖着鸭，照到三句答案！';$('action').textContent='帮鸭照下一句';$('status').textContent='禁止远光鸭。';}else{const n=notes.find(n=>!n.hit);if(n){duck.x=n.x;duck.y=n.y+155;collect()}}}else if(level===1){feed(books.findIndex(b=>!b.used))}else stamp();update();}
function collect(){if(level!==0||light||done)return;notes.forEach(n=>{if(!n.hit&&Math.hypot(n.x-duck.x,n.y-(duck.y-155))<115){n.hit=true;found++;burst(n.x,n.y,12);say(n.text,n.x,n.y);beep(310+found*90,.1)}});update();if(found===3)win();}
$('action').onclick=action;$('reset').onclick=()=>reset();$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`声音：${sound?'开':'关'}`;$('sound').setAttribute('aria-pressed',String(sound));if(sound)beep(220,.15)};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>reset(Number(b.dataset.level)));
function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.onpointerdown=e=>{const p=point(e);if(level>=3){extraDown(p,e);return}pressed={...p};canvas.setPointerCapture(e.pointerId);if(level===1&&!done){const i=books.findIndex(b=>!b.used&&Math.abs(b.x-p.x)<75&&Math.abs(b.y-p.y)<55);if(i>=0){drag={type:'book',i,start:{...books[i]}};return}}if(Math.hypot(p.x-duck.x,p.y-duck.y)<150){drag={type:'duck',dx:duck.x-p.x,dy:duck.y-p.y};beep(180,.08)}else if(level===0&&light&&p.y<140&&p.x>530)action();else if(level===2&&!done&&p.y<370)stamp();};
canvas.onpointermove=e=>{if(level>=3){extraMove(point(e));return}if(!drag)return;const p=point(e);if(drag.type==='duck'){duck.x=Math.max(90,Math.min(630,p.x+drag.dx));duck.y=Math.max(170,Math.min(525,p.y+drag.dy));collect()}else{books[drag.i].x=p.x;books[drag.i].y=p.y;}};
canvas.onpointerup=e=>{if(level>=3){extraUp(point(e));return}const p=point(e),tap=pressed&&Math.hypot(p.x-pressed.x,p.y-pressed.y)<18;if(drag?.type==='book'){const b=books[drag.i];if(tap||Math.hypot(b.x-duck.x,b.y-(duck.y-105))<140)feed(drag.i);else{b.x=drag.start.x;b.y=drag.start.y;}}else if(drag?.type==='duck'){if(level===2&&!done&&(duck.y<370||tap))stamp();else if(tap){say(done?'鸭已下班':'嘎。',duck.x,duck.y-150);burst(duck.x,duck.y-80,8);beep(140,.2)}}drag=null;pressed=null;};canvas.onpointercancel=()=>{if(level>=3){ex.drag=null;return;}if(drag?.type==='book'){books[drag.i].x=drag.start.x;books[drag.i].y=drag.start.y}drag=null;pressed=null;};
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=4;ctx.stroke()}}
function text(s,x,y,size=24,color='#282133',align='center'){ctx.fillStyle=color;ctx.font=`900 ${size}px "PingFang SC","Microsoft YaHei",sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(s,x,y)}
function draw(now){let dt=Math.min((now-last)/1000,.035)||.016;last=now;t+=dt;ctx.clearRect(0,0,W,H);ctx.fillStyle=level===0&&!light?'#25233c':'#fff3cb';ctx.fillRect(0,0,W,H);
ctx.strokeStyle=level===0&&!light?'#36324e':'#e9dba9';ctx.lineWidth=2;for(let y=50;y<H;y+=52){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}
if(level>=3)drawExtra();
if(level===0){if(light){text('既然闭眼都会',360,160,37);text('灯：那我走？',360,210,25,'#9c6e5f');rounded(552,30,115,72,16,'#ffe14d','#282133');text('关灯',610,66,26);}else{const g=ctx.createRadialGradient(duck.x,duck.y-155,10,duck.x,duck.y-155,150);g.addColorStop(0,'#ffeb8366');g.addColorStop(1,'#ffeb8300');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(const n of notes){let near=Math.hypot(n.x-duck.x,n.y-(duck.y-155));if(!n.hit){ctx.globalAlpha=near<190?1:.18;rounded(n.x-53,n.y-30,106,60,14,'#ffe14d');text(n.text,n.x,n.y,29);ctx.globalAlpha=1;}}if(!done)text('拖动鸭鸭，让头灯照到答案',360,580,23,'#e3d8fd');}}
if(level===1){text(done?'知识使鸭沉重':'今日份知识，请签收',360,90,32);if(!done){text('投喂区 ↓',360,160,21,'#946651');ctx.setLineDash([8,8]);ctx.strokeStyle='#df77a1';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(duck.x,duck.y-100,105+eaten*24,85+eaten*12,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}}
if(level===2){rounded(60,45,600,285,15,'#31695e','#282133');text('请在此处发表鸭见',360,93,23,'#e3f0ca');for(let i=0;i<stamps;i++){ctx.save();ctx.translate(155+(i%3)*202,172+Math.floor(i/3)*97);ctx.rotate(Math.sin(i*5)*.22);text('嘎',0,0,74,['#fff9ed','#ffe14d','#ffa8cd'][i%3]);ctx.restore();}if(!stamps)text('把鸭拖到这里',360,214,35,'#ffffff99');}
ctx.save();if(level>=3){ctx.globalAlpha=0;}let sx=1+eaten*.16,sy=1+eaten*.08,angle=0;let dy=0;if(!drag){dy=Math.sin(t*3)*5}if(done&&level===1){angle=Math.min((t-winTime)*2,1.3);dy+=Math.min((t-winTime)*35,35)}if(level===2&&stamps)angle=Math.sin(t*15)*.12;if(done&&level!==1){sx+=Math.sin(t*8)*.025;sy-=Math.sin(t*8)*.025}ctx.translate(duck.x,duck.y+dy);ctx.rotate(angle);ctx.scale(sx,sy);if(art.complete&&art.naturalWidth)ctx.drawImage(art,-145,-160,290,290);if(level===0&&!light){ctx.shadowColor='#fff76e';ctx.shadowBlur=25;rounded(-47,-77,30,15,8,'#fff99a');rounded(13,-77,30,15,8,'#fff99a');ctx.shadowBlur=0;}ctx.restore();
if(level===1){books.forEach((b,i)=>{if(!b.used){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(drag?.i===i?-.12:Math.sin(i)*.06);rounded(-68,-43,136,86,13,['#ff90ba','#88d9c6','#a9b8ff'][i],'#282133');text(b.name,0,0,28);ctx.restore()}})}
if(done&&level<3&&level!==1){rounded(164,level===2?355:70,392,64,18,'#ffe14d','#282133');text(['闭眼不会，开灯会','知识使鸭沉重','本题答案：嘎嘎嘎'][level],360,level===2?387:102,30);}
particles=particles.filter(p=>p.life>0);for(let p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=700*dt;p.rotation+=dt*5;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation);ctx.globalAlpha=Math.min(1,p.life);ctx.fillStyle=p.color;ctx.fillRect(-6,-6,12,18);ctx.restore();}floaters=floaters.filter(f=>f.life>0);for(let f of floaters){f.life-=dt;f.y-=dt*24;ctx.globalAlpha=Math.min(1,f.life);text(f.text,f.x,f.y,32,level===0&&!light?'#fff9db':'#dc3984');ctx.globalAlpha=1;}requestAnimationFrame(draw);}
reset();requestAnimationFrame(draw);
const modelContext=document.modelContext;if(modelContext?.registerTool){try{modelContext.registerTool({name:'get_duck_school_state',description:'Read current duck school lesson and progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({lesson:level+1,completed:done,credits:won.size,found,eaten,stamps,progress:level>=3?extraProgress():null})});modelContext.registerTool({name:'start_duck_school_lesson',description:'Start or restart one of the eight duck school lessons.',inputSchema:{type:'object',properties:{lesson:{type:'integer',minimum:1,maximum:8}},required:['lesson'],additionalProperties:false},execute:input=>{if(!Number.isInteger(input?.lesson)||input.lesson<1||input.lesson>8)throw new Error('lesson must be an integer from 1 to 8');reset(input.lesson-1);return{lesson:level+1,completed:false}}});}catch(e){console.warn('Optional game tools unavailable',e)}}

function options(items,fn){$('options').replaceChildren(...items.map((name,i)=>{const b=document.createElement('button');b.textContent=name;b.onclick=()=>fn(i);return b}));}
function startExtra(){ex={hits:0,mistakes:0,phase:0,selected:-1,drag:null,start:t};duck={x:360,y:500};$('status').textContent='这次得动点真本事。';
if(level===3){ex.good=Math.floor(Math.random()*4);ex.caught=[];$('hint').textContent='戳到移动的“重点”三次。小心“重咸”和“重点？”！';$('action').textContent='慢一点看';options(['①','②','③','④'],hitTarget);}
if(level===4){ex.sequence=Array.from({length:4},()=>Math.floor(Math.random()*3));ex.recall=0;ex.show=true;ex.start=t;$('hint').textContent='记住鸭依次讲的四个词；讲完按顺序点回来。';$('action').textContent='再讲一遍';options(['语文','数学','英语'],memoryPick);}
if(level===5){ex.cell=[0,4];ex.key=false;ex.checkpoint=false;ex.cool=0;duck={x:140,y:490};$('hint').textContent='点相邻格移动：先拿“重点”，再到出口。避开粉红检查格！';$('action').textContent='等一等，观察检查';options(['左移','上移','下移','右移'],i=>gridMove([[-1,0],[0,-1],[0,1],[1,0]][i]));}
if(level===6){ex.order=[3,1,0,2];ex.cards=[{id:0,x:130,y:485},{id:1,x:285,y:485},{id:2,x:440,y:485},{id:3,x:595,y:485}];ex.slots=[null,null,null,null];ex.selected=-1;$('hint').textContent='照课表顺序排好四本书。拖到格子；或先点书，再点位置。';$('action').textContent='检查课表';options(['语文','数学','英语','体育'],selectSort);}
if(level===7){ex.phase=0;ex.book={x:350,y:180};ex.boardX=360;ex.hasBook=false;ex.drag=null;ex.start=t;$('hint').textContent='综合题：先关灯找到真正的“重点”。';$('action').textContent='关灯找重点';options([],()=>{});}
}
function extraProgress(){if(done)return '本节：超额完成';return level===3?`抓住重点 ${ex.hits} / 3`:level===4?(ex.show?'先听，别急着答':`记住顺序 ${ex.recall} / 4`):level===5?(ex.key?'已拿重点 · 去出口':'先去黄色格拿重点'):level===6?`课表就位 ${ex.slots.filter(x=>x!==null).length} / 4`:`综合任务 ${ex.phase} / 3`;}
function winExtra(){done=true;winTime=t;won.add(level);burst(360,260,70);beep(440,.3);$('status').textContent=['','','','鸭：重点会跑，怪我？','鸭的脑子，偶尔在线。','重点送达，神也没走。','体育终于没有被占课。','恭喜，学已被鸭上明白了。'][level];$('hint').textContent=['','','','抓住了重点。其他的，交给明天的鸭。','老师：不是说只讲一遍？ 鸭：你说你的。','绕过检查，带着重点走出精神内耗。','四本书，各就各位。鸭想把自己排到放学。','八节课全体验。人类已解放，鸭鸭申请带薪休假。'][level];$('action').textContent=level===7?'放学！回第一节':'下节课，继续挑战';options([],()=>{});update();}
function miss(msg){ex.mistakes++;say(msg,360,105);beep(110,.15);$('status').textContent=msg;}
function targetPositions(){return Array.from({length:4},(_,i)=>({x:145+(i%2)*405+Math.sin(t*(ex.slow?0.5:1.05)+i*2)*55,y:200+Math.floor(i/2)*160+Math.cos(t*.9+i)*30}));}
function hitTarget(i){if(done||level!==3)return;if(i===ex.good){ex.hits++;burst(targetPositions()[i].x,targetPositions()[i].y,20);beep(340,.15);if(ex.hits===3){win();return}ex.good=(ex.good+1+Math.floor(Math.random()*3))%4;say('重点换地方了！',360,100)}else{ex.hits=Math.max(0,ex.hits-1);miss('抓错了，退一格再来');}update();}
function memoryPick(i){if(done||level!==4)return;if(ex.show){$('status').textContent='先听完四个词。';return}if(i===ex.sequence[ex.recall]){ex.recall++;beep(240+i*100,.13);if(ex.recall===4)win()}else{miss('串台了！再听一次');ex.recall=0;ex.show=true;ex.start=t;}update();}
const walls=[[1,4],[1,3],[3,2],[3,1],[1,1]];
function guardCell(){return [2,Math.floor(t/1.8)%3+1]}
function gridMove(delta){if(done||level!==5)return;const [x,y]=ex.cell;const n=[x+delta[0],y+delta[1]];if(n[0]<0||n[0]>4||n[1]<0||n[1]>4||walls.some(c=>c[0]===n[0]&&c[1]===n[1])){beep(100,.08);return}const g=guardCell();if(n[0]===g[0]&&n[1]===g[1]){miss('被抓走神！回检查点');ex.cell=ex.checkpoint?[0,2]:[0,4];}else{ex.cell=n;if(n[0]===0&&n[1]===2)ex.checkpoint=true;if(n[0]===4&&n[1]===4){ex.key=true;say('重点拿到！',360,110)}if(n[0]===4&&n[1]===0){if(ex.key)win();else miss('先把重点带上呀');}}update();}
function selectSort(i){if(done||level!==6)return;ex.selected=i;options(['放①','放②','放③','放④'],placeSort);$('status').textContent=`已拿起${['语文','数学','英语','体育'][i]}`;}
function placeSort(slot){if(done||level!==6||ex.selected<0)return;const id=ex.selected;const old=ex.slots.indexOf(id);if(old>=0)ex.slots[old]=null;ex.slots[slot]=id;ex.selected=-1;options(['语文','数学','英语','体育'],selectSort);beep(220,.08);update();}
function extraAction(){if(level===3){ex.slow=!ex.slow;$('action').textContent=ex.slow?'恢复正常速度':'慢一点看'}if(level===4){ex.recall=0;ex.show=true;ex.start=t;update()}if(level===5){$('status').textContent='检查格每隔一会儿就会换位置。'}if(level===6){if(ex.order.every((id,i)=>ex.slots[i]===id))win();else{const correct=ex.order.filter((id,i)=>ex.slots[i]===id).length;miss(`有 ${correct} 本对了，再调一调`);}}if(level===7){if(ex.phase===0){ex.phase=1;ex.start=t;$('hint').textContent='拖鸭移动头灯。照亮“重点”后点它；别拿“重咸”。';$('action').textContent='头灯左移';options(['头灯左移','头灯右移','拿重点'],i=>{if(i<2)duck.x=Math.max(100,Math.min(620,duck.x+(i?65:-65)));else takeFinalBook();});}else if(ex.phase===1){duck.x=Math.max(100,duck.x-65);}else if(ex.phase===2){feedFinal()}else if(ex.phase===3){submitFinal()};update();}}
function finalBookX(){return 360+Math.sin(t*.65)*205}
function takeFinalBook(){if(done||level!==7||ex.phase!==1)return;const x=finalBookX();if(Math.abs(duck.x-x)>100){miss('灯没照到，先挪鸭');return}ex.phase=2;ex.book={x,y:240};$('hint').textContent='把这本重点拖到鸭头上。别喂给旁边的检查格。';$('action').textContent='喂给鸭脑子';options([],()=>{});say('真重点到手！');update();}
function feedFinal(){if(level!==7||ex.phase!==2||done)return;ex.phase=3;duck={x:360,y:480};$('hint').textContent='最后，把鸭拖到移动的黑板上。等检查员闪开再交卷！';$('action').textContent='交卷！';options(['鸭向左','鸭向右'],i=>duck.x=Math.max(90,Math.min(630,duck.x+(i?60:-60))));burst(duck.x,duck.y-100,20);update();}
function boardX(){return 360+Math.sin(t*.6)*185}function checking(){return Math.sin(t*1.3)>.65}
function submitFinal(){if(done||level!==7||ex.phase!==3)return;if(checking()){miss('检查中，等它转身！');duck.y=480;return}if(Math.abs(duck.x-boardX())>105){miss('没对准黑板，挪近一点');duck.y=480;return}win();}
function extraDown(p,e){if(done){say('嘎，下课啦',p.x,p.y);return}canvas.setPointerCapture(e.pointerId);ex.press=p;if(level===3){const pts=targetPositions();const i=pts.findIndex(q=>Math.abs(q.x-p.x)<83&&Math.abs(q.y-p.y)<49);if(i>=0)hitTarget(i)}if(level===4){if(p.y>420&&p.y<540){const i=Math.floor((p.x-60)/200);if(i>=0&&i<3)memoryPick(i)}}if(level===5){const x=Math.round((p.x-140)/110),y=Math.round((p.y-150)/85);const dx=x-ex.cell[0],dy=y-ex.cell[1];if(Math.abs(dx)+Math.abs(dy)===1)gridMove([dx,dy]);else $('status').textContent='一次走一格；点相邻空格。';}if(level===6){if(p.y>190&&p.y<320&&ex.selected>=0){const slot=Math.floor((p.x-55)/155);if(slot>=0&&slot<4)placeSort(slot);return}const i=ex.cards.findIndex(c=>Math.abs(c.x-p.x)<67&&Math.abs(c.y-p.y)<45);if(i>=0){selectSort(i);ex.drag={kind:'sort',id:i,x:p.x,y:p.y}}}if(level===7){if(ex.phase===1){if(p.y<300&&Math.abs(p.x-finalBookX())<80){takeFinalBook()}else if(p.y>300)ex.drag={kind:'duck'}}if(ex.phase===2&&Math.hypot(p.x-ex.book.x,p.y-ex.book.y)<90)ex.drag={kind:'book'};if(ex.phase===3&&Math.hypot(p.x-duck.x,p.y-duck.y)<130)ex.drag={kind:'duck'};}}
function extraMove(p){if(!ex.drag||done)return;if(ex.drag.kind==='sort'){ex.drag.x=p.x;ex.drag.y=p.y;}if(ex.drag.kind==='duck'){duck.x=Math.max(90,Math.min(630,p.x));if(ex.phase===3)duck.y=Math.max(190,Math.min(520,p.y));}if(ex.drag.kind==='book'){ex.book.x=p.x;ex.book.y=p.y;}}
function extraUp(p){if(!ex.drag||done)return;const kind=ex.drag.kind;if(kind==='sort'&&p.y>175&&p.y<335){const slot=Math.floor((p.x-55)/155);if(slot>=0&&slot<4)placeSort(slot)}if(kind==='book'){if(Math.hypot(p.x-duck.x,p.y-(duck.y-80))<125)feedFinal();else ex.book={x:360,y:240};}if(kind==='duck'&&level===7&&ex.phase===3&&p.y<310)submitFinal();ex.drag=null;}
function drawSmallDuck(x,y,size=145){if(art.complete&&art.naturalWidth)ctx.drawImage(art,x-size/2,y-size/2,size,size)}
function drawExtra(){if(done){drawSmallDuck(360,345,300);rounded(115,90,490,80,18,'#ffe14d','#282133');text(level===7?'准予放鸭！':'本节，鸭过关了！',360,130,36);text(`已拿下 ${won.size} / 8 节课`,360,570,26);return}
if(level===3){text('抓重点，不抓重咸',360,75,31);const names=['重咸','重点？','自学'];targetPositions().forEach((p,i)=>{rounded(p.x-83,p.y-46,166,92,18,i===ex.good?'#ffe14d':'#ffa7c9','#282133');text(i===ex.good?'重点':names[(i+ex.good)%3],p.x,p.y,31);text(String(i+1),p.x,p.y+67,22,'#756373')});drawSmallDuck(360,550,115);}
if(level===4){if(ex.show&&t-ex.start>5.3){ex.show=false;ex.recall=0;$('status').textContent='轮到鸭了，按顺序！';update()}text(ex.show?'先听课，别抢答':'鸭，请开始你的复述',360,85,29);const index=Math.floor((t-ex.start)/1.3);rounded(150,170,420,155,25,'#31695e','#282133');text(ex.show&&index<4?['语文','数学','英语'][ex.sequence[index]]:'？ ？ ？ ？',360,245,48,'#fff9ed');text(ex.show?`${Math.min(index+1,4)} / 4`:`已记住 ${ex.recall} / 4`,360,365,25);['语文','数学','英语'].forEach((n,i)=>{rounded(60+i*200,435,180,92,16,'#ffadd0','#282133');text(n,150+i*200,481,29)});}
if(level===5){text('先拿重点，再走出口',360,55,29);const g=guardCell();for(let y=0;y<5;y++)for(let x=0;x<5;x++){const wall=walls.some(c=>c[0]===x&&c[1]===y),guard=g[0]===x&&g[1]===y;rounded(91+x*110,111+y*85,98,74,12,wall?'#d1d7df':guard?'#fb7eb1':x===4&&y===4&&!ex.key?'#ffe14d':'#fff9ed','#282133');if(wall)text('走神',140+x*110,150+y*85,20,'#687380');else if(guard)text('检查',140+x*110,150+y*85,20);if(x===4&&y===0)text('出口',580,150,21);if(x===4&&y===4&&!ex.key)text('重点',580,490,21);if(x===0&&y===2)text('存档',140,320,20,'#927855');}drawSmallDuck(140+ex.cell[0]*110,150+ex.cell[1]*85,80);text('黄色格拿重点 · 粉红格等一等',360,580,23);}
if(level===6){text('今日课表：体育 → 数学 → 语文 → 英语',360,75,25);['①','②','③','④'].forEach((n,i)=>{rounded(55+i*155,200,143,115,16,'#e4f3ff','#282133');text(ex.slots[i]===null?n:['语文','数学','英语','体育'][ex.slots[i]],126+i*155,258,28);});ex.cards.forEach(c=>{if(ex.drag?.kind==='sort'&&ex.drag.id===c.id)return;rounded(c.x-65,c.y-43,130,86,14,ex.selected===c.id?'#ffe14d':'#ffadd0','#282133');text(['语文','数学','英语','体育'][c.id],c.x,c.y,25)});if(ex.drag?.kind==='sort'){rounded(ex.drag.x-65,ex.drag.y-43,130,86,14,'#ffe14d','#282133');text(['语文','数学','英语','体育'][ex.drag.id],ex.drag.x,ex.drag.y,25)}text('排完后，点“检查课表”',360,585,24);}
if(level===7){if(ex.phase===0){text('头灯 + 投喂 + 交卷',360,120,35);text('这次，三个动作得连起来。',360,185,25);drawSmallDuck(360,430,230)}if(ex.phase===1){ctx.fillStyle='#25233c';ctx.fillRect(0,0,W,H);const x=finalBookX();let g=ctx.createRadialGradient(duck.x,200,15,duck.x,200,140);g.addColorStop(0,'#ffec8477');g.addColorStop(1,'#ffec8400');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=Math.abs(duck.x-x)<110?1:.14;rounded(x-74,160,148,85,14,'#ffe14d');text('重点',x,202,31);ctx.globalAlpha=.45;text('重咸',720-x,280,29,'#f991bd');ctx.globalAlpha=1;drawSmallDuck(duck.x,480,170);text('拖鸭左右挪头灯，再点真正的重点',360,590,21,'#fff9ed')}if(ex.phase===2){text('把重点装进鸭脑子',360,80,31);drawSmallDuck(duck.x,duck.y,240);rounded(ex.book.x-75,ex.book.y-45,150,90,15,'#ffe14d','#282133');text('重点',ex.book.x,ex.book.y,32);text('拖这本书到鸭头上',360,585,24)}if(ex.phase===3){const x=boardX();rounded(x-117,100,234,155,17,checking()?'#f97db3':'#31695e','#282133');text(checking()?'检查中…':'可以交卷',x,147,27,checking()?'#282133':'#fff9ed');text(checking()?'先别来':'鸭请对准我',x,208,21,checking()?'#282133':'#fff9ed');drawSmallDuck(duck.x,duck.y,170);text('检查员不看时，送鸭上黑板',360,590,23);}}}
